sudo: true
language: node_js
node_js:
- 5.11.1
before_install:
- if [ "${TRAVIS_NODE_VERSION}" == "0.8" ]; then npm install -g npm@2.11.1; fi
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
- node --version
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- pwd
- npm install
- npm install bower
- bower install

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- rackup  # start a Web server
- sleep 3 # give Web server some time to bind to sockets, etc

script:
- ls
- gulp test
- gulp build
after_script:
- echo ran script
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com/ng-nj.org.git" > .git/credentials
- echo 'Success'
- ls
- git config --global user.email "mrdotjim@gmail.com"
- git config --global user.name "JimTheMan"
- bash ./deploy.sh
- echo Sent to gh-pages!
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
    - irc.freenode.orgi#unshift
    on_success: change
    on_failure: change
env:
  global:
  - GH_REF: github.com/ng-nj/ng-nj.org.git
  - secure: SYSJERymKf2YiJPculxBGF2C7g2CA9aSZNTYorCHZUpGjsooJGZnw4CFrioK9ElhIQNAZV/dne9CMNw531w8/bB2VOMvXDS26m0lSJZTN86mKpz5+IT7uQ+96ObUpBslxZ8J2+SiYAwvjXKmfrFIYNuT/cwUHAgDEARRdVZbMLfGupIszD9H0whMUnZQEimC75IyY7GB+35ZJov3OgpTsN4LQfkhwNkzX7J3vt2hGrO92hgtvAO7eINLvtTycaqQNpDjxr6dv5XEzPm8M3YqDOEjv/BFDuG6hGnORe15SPiPo3/kOHKv/fN+SbjSsk/5zIxCxUmIWQTQMhtDWyoBaUesKQO8PCKwMIbjxZh3xnA4fJ/QkVJUe6xz8yzsdE184r/n97Rv9RkcZCY7iIGbp17hpavgfooJ0qFhfgPyU18XaxAYiK0SFie+XLXEAm6BMWRmjASNZ0YEShgzbjzsRfhohF2teGOxh4DMce4UnCIl28brXMUjo1j7ptLMls6C/zjU8h94r/q5rsISzkkTQjdJRlp4mLyeBbqW/tVef5VSgkFnDKy2qScpG6n0LYQW1bAHv/NnB0/80jZD+JpeuAwUjvSjFpWWFC0b4iwLuiziRAQFXw6KUhNBX+7cho9k03Erl543qFXhothQOSmixF2Co1GeaH9Ps1DKuQk9O5M=
